### ISSUE TITLE
Deprecation with posts in Jekyll 3

### ISSUE THREAD

**Issue by heathervv** [multunus/jekyll-author-plugin#9]
I started getting a warning on `jekyll serve`:

```
Deprecation: Collection#each should be called on the #docs array directly.
Called by /my-project/_plugins/author_generator.rb:76:in `write_author_indexes'.
```

I googled around a bit and found that it has something to do with posts being considered documents in Jekyll 3 (https://github.com/asciidoctor/jekyll-asciidoc/issues/35)

I resolved the issue simply by changing line 76 on my local to say: `self.posts.docs.each do |post|` however there should be a conditional check for jekyll 3 to allow for backwards compatibility. While I'm slowly teaching myself ruby, I am by no means good at it, and have no idea how to do a conditional check.

Depending on how quickly this issue is tackled, I'll fork and attempt to tackle this myself!

**Comment by leenasn** [comment]
You should be able to check the version using the `Jekyll::VERSION`. Similar code is being used in [Jekyll Redirect](https://github.com/jekyll/jekyll-redirect-from/blob/838599da32b2cbdd026d33b23f88afe31d832e55/lib/jekyll-redirect-from/redirector.rb#L7) too.

Feel free to submit a Pull Request with the above code, so that I can merge the same.
